change to WebView and add link auto detection on writing
gsainfoteam/ziggle-flutter pull request #140
Opened 2024-01-11 03:46 UTC by dohyun-ko

2024-01-11 03:47 UTC, 2paperstar commented
저번에 회의에서 나온 웹뷰 버그는 해결 되었나요?

2024-01-13 06:27 UTC, dohyun-ko commented
웹뷰 버그는 여전히 오리무중입니다... 크래시 로그를 해독할 수가 없어요

2024-01-13 06:39 UTC, 2paperstar commented
iOS Podfile.lock도 업데이트 해주세요 (ios 시뮬에서 한번 돌려주시면 됩니당)
-> 돌려봤는데 여기도 웹뷰 버그가 있는 것 같네요,,

2024-01-13 06:41 UTC, 2paperstar requested changes
웹뷰 높이를 동적으로 잡는게 제대로 안 되는 것 같아요 (무한루프 도는 느낌?)

2024-01-17 00:57 UTC, 2paperstar commented
개인적으로 `flutter_inappwebview`의 DX가 더 좋더라고요
웹뷰는 #147 에서 이어서 작업하고, link auto detection은 다른 PR에서 붙이겠습니다!

2024-02-13 13:23 UTC, closed without merging

2024-02-13 13:23 UTC, 2paperstar commented
suppressed by #214