Ziggle App Design Renewal
gsainfoteam/ziggle-flutter pull request #249
Opened 2024-05-10 22:59 UTC by no-ikjun

![image](https://github.com/gsainfoteam/ziggle-flutter/assets/96350366/5efda88c-7e6d-44ff-aa92-603703399b93)
![image](https://github.com/gsainfoteam/ziggle-flutter/assets/96350366/47d388b8-9e8c-4d58-8627-0e36fb683a2e)
![image](https://github.com/gsainfoteam/ziggle-flutter/assets/96350366/7f94c818-7fbb-4f03-baba-85499ff8005f)

- feed page 디자인 새롭게 수정하였습니다.
- 마이 페이지 디자인 약간 수정하였습니다.
- 마이 페이지 및 정보 페이지 ListTile 위젯의 splash 색상을 투명으로 설정하였습니다.

2024-05-11 01:42 UTC, 2paperstar requested changes

2024-05-11 01:42 UTC, 2paperstar commented on ios/Podfile.lock
`bundle exec pod install` 처럼 써주세요!

2024-05-11 01:42 UTC, 2paperstar commented on lib/app/modules/auth/presentation/pages/profile_page.dart
> +                    FontWeight.w400),
_buildInfo 말고 Text 바로 쓰기

2024-05-11 01:42 UTC, 2paperstar commented on lib/app/modules/notices/presentation/pages/feed_page.dart
> +      separatorBuilder: (context, index) => Container(),
SliverList.separated -> SliverList.builder 로 바꿔서 separatorBuilder를 없애주세요

2024-05-11 01:42 UTC, 2paperstar commented on lib/app/modules/notices/presentation/pages/notice_page.dart
> +                    Assets.images.defaultProfile.image(width: 40, height: 40),
profile circle.svg 파일은 지워주세요

2024-05-11 01:42 UTC, 2paperstar commented on lib/app/modules/notices/presentation/widgets/notice_card.dart
> +              // ),
이건 왜 주석인가요?

2024-05-11 01:42 UTC, 2paperstar commented on lib/app/modules/auth/presentation/pages/profile_page.dart
> +      splashColor: Colors.transparent,
theme.dart 파일에 `splashColor: Colors.transparent` 넣으면 안 되나요?

2024-05-11 02:16 UTC, no-ikjun commented on lib/app/modules/notices/presentation/widgets/notice_card.dart
> +              // ),
디자인 리뉴얼할 때 내용은 무조건 클릭해야 보이게 하는 걸로 의도하긴 했죠

2024-05-11 05:33 UTC, 2paperstar commented on lib/app/modules/notices/presentation/widgets/notice_card.dart
> +              // ),
그러면 없어도 되는거 아닌가

2024-05-11 05:33 UTC, 2paperstar requested changes

2024-05-11 05:33 UTC, 2paperstar commented on lib/app/modules/setting/presentation/pages/about_page.dart
> +                  splashColor: Colors.transparent,
여기도 다 빼주쇼..요

2024-05-11 05:47 UTC, no-ikjun commented on lib/app/modules/notices/presentation/widgets/notice_card.dart
> +              // ),
나중에 또 불만이 접수되면 다시 사용될 수 있으니 일단 남겨두는게 좋지 않을까..라는 생각

2024-05-14 15:11 UTC, 2paperstar approved these changes

2024-05-14 15:11 UTC, 2paperstar commented on pubspec.yaml
>  version: 3.1.3
요기 버전만 3.2.0? 그런식으로 바꾸고 PR 머지하면 될듯 합니당

2024-05-14 15:11 UTC, 2paperstar commented on lib/app/values/strings.dart
> +  static const _idpClientId = 'ziggle_stg';
이거 production이랑 staging이랑 따로 가져가야 할 것 같은데..

2024-05-15 05:03 UTC, merged