268 feature group detail page
gsainfoteam/ziggle-flutter pull request #273
Opened 2024-09-02 02:11 UTC by dawnfire05

2024-09-02 02:21 UTC, 2paperstar requested changes

2024-09-02 02:21 UTC, 2paperstar commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +              return <Widget>[
```suggestion
            headerSliverBuilder: (context, innerBoxIsScrolled) => [
```

2024-09-02 02:21 UTC, 2paperstar commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +                  builder: (context) {
이거 왜 있는거죠?

2024-09-02 02:21 UTC, 2paperstar commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +                        SliverList.builder(
ListView 써도 될 것 같습니다 (대신에 single child scroll view?)

2024-09-02 02:21 UTC, 2paperstar commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +                crossAxisAlignment: CrossAxisAlignment.start,
정렬이 안 맞아요

2024-09-02 02:21 UTC, 2paperstar commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +              color: const Color(0xFFF7F7F7),
이거 팔레트에 비슷한 색 있지 않나요?

2024-09-02 02:21 UTC, 2paperstar commented on lib/app/modules/notices/presentation/pages/feed_page.dart
이 파일 변경사항은 빼주세요

2024-09-02 02:28 UTC, dawnfire05 commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +                  builder: (context) {
아 기존에 NestedScrollView 기능 테스트할 때 작성했던 코드에요.
지금은 필요 없습니다. 삭제할게용~

2024-09-02 02:30 UTC, dawnfire05 commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +                crossAxisAlignment: CrossAxisAlignment.start,
오잉 맞지 않나요
<img width="461" alt="image" src="https://github.com/user-attachments/assets/6ef92545-e473-4155-b2f1-d73c2ceaa712">
없으면 이렇게 되는디

2024-09-02 02:33 UTC, dawnfire05 commented on lib/app/modules/notices/presentation/pages/feed_page.dart
넹

2024-09-13 11:57 UTC, 2paperstar commented on lib/app/modules/groups/presentation/pages/group_detail_page.dart
> +                crossAxisAlignment: CrossAxisAlignment.start,
뭐지 폰으로 봐서 그랬나보다

2024-09-13 11:57 UTC, 2paperstar commented
close하고 v4로 다시 진행하시죠!

2024-09-17 08:10 UTC, 2paperstar commented
suppressed by #375

2024-09-17 08:10 UTC, closed without merging