feat: add ziggleCheckbox
gsainfoteam/ziggle-flutter pull request #295
Opened 2024-09-06 12:59 UTC by GwanLiZa

[ziggleCheckbox.webm](https://github.com/user-attachments/assets/6fb0bb05-d2fe-41c4-9008-cace5b70f02c)

2024-09-06 13:33 UTC, 2paperstar requested changes

2024-09-06 13:33 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +            duration: const Duration(milliseconds: 300),
다른 위젯에서는 100ms를 트랜지션 타임으로 사용하고 있는데, 300을 특별히 사용한 이유가 있나요?

2024-09-06 13:33 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +              Icons.check,
이렇게 말고 직접 svg 파일 사용해주새요
아직 관련된 PR이 머지되지 않아서 사용법은 다른 PR에서 참고할 수 있을거에요

2024-09-06 13:33 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +  final double size;
너무 자유도를 주면 잘못된 use case가 생길 수 있어요
다른 구현이 필요하면 enum 을 사용해주세요

2024-09-06 16:47 UTC, GwanLiZa commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +            duration: const Duration(milliseconds: 300),
100ms로 시정하겠습니다.

2024-09-06 16:49 UTC, GwanLiZa commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +  final double size;
다른 구현이 필요하지 않다면, 바로 색상을 사용하여도 괜찮은가요?

2024-09-06 16:49 UTC, GwanLiZa commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +              Icons.check,
넵, 참고하겠습니다.

2024-09-06 17:04 UTC, GwanLiZa commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +              Icons.check,
figma에 이 친구가 icon이 아닌 것 같은데, 다른 위젯에 있는거로 사용할까요?

2024-09-07 13:32 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +  final double size;
저는 그렇게 생각하긴했는데 (이게 플러터 내장 위젯 처럼 제너럴하게 쓰이는게 아니기 때문에) 어떻게 생각하세요?

2024-09-07 13:39 UTC, GwanLiZa commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +  final double size;
저는 혹시나 트레이드 컬러 같은 게 바뀌었을 때, 보수하기 편하지 않을까 해서 저렇게 작성했던 것인데
그렇게 많은 코드가 수정되는게 아니어서 잘못된 use case 방지하는게 더 좋아보이네요.

2024-09-07 13:41 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_checkbox.dart
> +  final double size;
넹 저도 그런 의견입니다

2024-09-07 13:42 UTC, 2paperstar approved these changes

2024-09-07 14:17 UTC, merged