feat: add ZiggleToggleButton
gsainfoteam/ziggle-flutter pull request #298
Opened 2024-09-06 16:45 UTC by GwanLiZa

[ziggleToggle.webm](https://github.com/user-attachments/assets/44d15cc7-37d8-404b-8a63-8e1262808a7a)

2024-09-06 17:00 UTC, 2paperstar requested changes

2024-09-06 17:00 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_toggle_button.dart
> +  final ValueChanged<bool> onToggle;
앞에서는 정신 없어서 코멘트를 못 남겼는데 이 타입 좋네요!

2024-09-06 17:00 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_toggle_button.dart
> +  final double thumbSize;
체크박스랑 동일한 코멘트입니다
사용하는 쪽에 너무 자유도를 주지 마세요!

아니면 이 constructor를 private으로 만들고, factory method들을 만드는 것도 방법일 것 같아요!!

2024-09-06 17:00 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_toggle_button.dart
> +              left: _switched ? widget.trackWidth - widget.thumbSize - 3 : 3,
left만 쓰지 말고 right속성도 써보세요!

2024-09-07 06:18 UTC, GwanLiZa commented on lib/app/modules/common/presentation/widgets/ziggle_toggle_button.dart
> +              left: _switched ? widget.trackWidth - widget.thumbSize - 3 : 3,
[ziggleToggle2.webm](https://github.com/user-attachments/assets/673adda6-a1ca-446f-bbd3-fc09073b9780)

`left: _switched ? null : 3,`
`right: _switched ? 3 : null,`
              
@2paperstar right 속성도 같이 쓰면 확실히 위치 표기가 간단하긴한데
애니메이션이 적용이 안되는 것 같아요!

2024-09-07 16:28 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_toggle_button.dart
> +              left: _switched ? widget.trackWidth - widget.thumbSize - 3 : 3,
이거말고 AnimatedAlign을 써볼래요?

2024-09-13 07:30 UTC, 2paperstar approved these changes

2024-09-13 13:30 UTC, merged