305 v4 ziggleinput
gsainfoteam/ziggle-flutter pull request #317
Opened 2024-09-07 11:51 UTC by dawnfire05

https://github.com/user-attachments/assets/3d9a599f-e357-4aa7-97bd-f75e9c3bf8fd

disabled 버젼도 있어요

2024-09-07 12:33 UTC, 2paperstar requested changes

2024-09-07 12:33 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_input.dart
> +  final TextEditingController c;
controller라는 이름 써주세요

2024-09-07 12:33 UTC, 2paperstar commented on lib/app/values/palette.dart
> +  static const lightGray = Color(0xffB3B3B3);
gray라는 컬러가 있어요

2024-09-07 12:33 UTC, 2paperstar commented on lib/app/values/palette.dart
> +  static const lightGrayLight = Color(0xffF5F5F7);
얘는 아직 색상이 이름으로 정의되어있지 않을건데, inline으로 컬러 사용해주세요

2024-09-07 12:33 UTC, 2paperstar commented on lib/main.dart
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}
```

이 내용으로 revert 해주세요

2024-09-07 12:33 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_input.dart
> +        color: widget.disabled ? Palette.grayBorder : Palette.primary,
disabled일때 gray boder이기도 하겠지만 focus 상태가 닐 때도 gray border여야할거에요

2024-09-07 12:39 UTC, dawnfire05 commented on lib/app/values/palette.dart
> +  static const lightGrayLight = Color(0xffF5F5F7);
Palette에 지정하지 말고
ziggle_input.dart 내에서 Color()로 사용하라는 말인거죠?

2024-09-07 12:43 UTC, GwanLiZa commented on lib/app/modules/common/presentation/widgets/ziggle_input.dart
> +        style: const TextStyle(fontWeight: FontWeight.bold),
FontWeight.bold가 아니라 normal로 해야할 것 같아요

2024-09-07 16:30 UTC, 2paperstar commented on lib/app/values/palette.dart
> +  static const lightGrayLight = Color(0xffF5F5F7);
네 맞아요

2024-09-07 16:32 UTC, 2paperstar requested changes

2024-09-07 16:32 UTC, 2paperstar commented on lib/app/modules/common/presentation/widgets/ziggle_input.dart
> +class ZiggleInput extends StatefulWidget {
stateful일 이유가 없는 것 같아요

2024-09-10 13:32 UTC, 2paperstar approved these changes

2024-09-10 14:01 UTC, merged