feat: add AgreementItem
gsainfoteam/ziggle-flutter pull request #328
Opened 2024-09-10 02:35 UTC by dawnfire05

https://github.com/user-attachments/assets/2d3fa310-82eb-46bb-90b8-487ca246fece

2024-09-10 18:56 UTC, inthree3 requested changes

2024-09-10 18:56 UTC, inthree3 commented on lib/app/modules/notice/presentation/widgets/consent_item.dart
> +class ConsentItem extends StatefulWidget {
ConsentItem이라는 이름이 제가 느끼기에 직관적이지 않은 것 같아요.!
올려주신 영상을 바탕으로 봤을 때는 AgreementCheckbox 같은 이름은 어떤가요?

2024-09-12 06:40 UTC, 2paperstar commented on lib/app/modules/notice/presentation/widgets/consent_item.dart
> +class ConsentItem extends StatefulWidget {
consent 자체가 동의(특별히 약관 등에 대하여)를 의미하는 데에 쓰이는 단어이기도하고, 일단 피그마상에는 그렇게 적혀있긴해요 (cc. @crown-3)
CheckBox가 조금 애매한게 진짜 네모 체크박스로 이해될 수도 있어서 AgreementItem 정도여도 괜찮지 않을까 싶어요.

아니면 사용 자체가 경고(?)의 용도니까 CautionChecker? 같은 이름도 좋고요
자유로운 의견 부탁드려요!

2024-09-12 06:43 UTC, dawnfire05 commented on lib/app/modules/notice/presentation/widgets/consent_item.dart
> +class ConsentItem extends StatefulWidget {
AgreementItem 괜찮네요!!

2024-09-13 12:45 UTC, 2paperstar requested changes

2024-09-13 12:45 UTC, 2paperstar commented on lib/app/modules/notice/presentation/widgets/consent_item.dart
> +  final bool isChecked;
바깥에서 체크된 상태를 알고 있어야합니다
onChanged를 넣어주고, Stateless 위젯으로 작업한 뒤에 마무리해주면 좋을 것 같아요

2024-09-13 12:47 UTC, 2paperstar commented on lib/app/modules/notice/presentation/widgets/consent_item.dart
> +        color: isChecked ? Palette.primaryLight : Palette.grayLight,
이거 AnimatedContainer써서 애니메이션 줘도 좋을 것 같아요

2024-09-13 14:23 UTC, dawnfire05 commented on lib/app/modules/notice/presentation/widgets/consent_item.dart
> +        color: isChecked ? Palette.primaryLight : Palette.grayLight,
알겠습니당

2024-09-13 14:50 UTC, 2paperstar submitted a review, later dismissed

2024-09-13 14:51 UTC, 2paperstar commented
머지하기 전에 notice write consent page에 이 위젯 추가해줘요!

2024-09-14 17:27 UTC, dawnfire05 commented
헉 뭔가 이상해졌어요

2024-09-14 21:14 UTC, 2paperstar commented
[33454b1](https://github.com/gsainfoteam/ziggle-flutter/pull/328/commits/33454b18cb1dd4e8a74dd4f81cee1806355bbf61) 커밋으로 돌아가서 `git rebase development` 로 머지한 뒤에 `git push --force` 해주세요

2024-09-17 11:16 UTC, 2paperstar commented
근데 얘가 AgreementItem이 될거면 이거 사용하는 페이지 이름도 agreement page가 되어야...겠네요?
NoticeWriteConsentPage -> NoticeWriteAgreementPage ?

2024-09-17 11:26 UTC, 2paperstar commented on lib/app/modules/notices/presentation/widgets/agreement_item.dart
> +      duration: Durations.medium1,
나중에 지글에서 쓰는 모든 디자인 시스템 상수화 시키면 좋겠네요 (duration, decoration, padding 등등..)

2024-09-17 11:27 UTC, 2paperstar commented
일단 이 친구는 #377 작업 때문에 머지하겠습니다!

2024-09-17 11:29 UTC, merged